trigger:
  branches:
    include:
      - '*'
    
pool: vmss-windows-2025

steps:
- powershell: wsl --version
  displayName: check wsl version

- powershell: wsl --install Ubuntu
  displayName: install wsl distro

